# Straightforward code to plot the FRAP curve generated by the export.py file (.csv)
# It will plot the average +- std of the normalized data

import pandas as pd
import matplotlib.pyplot as plt

csv_file_path = '/path/to/FRAP_data_give_name_here.csv' 
data = pd.read_csv(csv_file_path).groupby('Time (s)')['Normalized Intensity'].agg(['mean', 'std'])

fig, ax = plt.subplots(figsize=(5,6))

ax.plot(data.index, data['mean'],
        label='Average Intensity',
        color='purple') # We love pink

ax.fill_between(data.index, data['mean'] - data['std'],
                data['mean'] + data['std'],
                color='purple',
                alpha=0.1,
                label='Standard Deviation')

ax.set_xlabel('Time (s)')
ax.set_ylabel('Normalized Intensity')
ax.set_title('FRAP Analysis')
ax.set_xlim()
ax.legend() 

plt.show()
